### ISSUE TITLE
Strapi Plugin - March-1 Milestone

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#24]
## Description

This is the list of goals to be achieved for March 1 milestone.

## Goals

- [ ] Implementation of all 10 Endpoints for both the use cases in Strapi plugin - Product and service (time booking).
- [ ] Postman collection for all 10 endpoints and both the use cases.
- [ ] Unit test cases for all 10 endpoints.
- [ ] Testing all 10 endpoints and demo of the end-to-end functionality, taking one use case for each scenario.
- [ ] Development of machine simulation code for Industry 4.0.
- [ ] Plugin development for Industry 4.0.

## Expected Outcome

NA

## Acceptance Criteria

NA
## Implementation Details

NA
## Mockups / Wireframes

NA
---

### Product Name

NA
### Project Name

NA
### Organization Name:

NA
### Domain

NA
### Tech Skills Needed:

NA
### Complexity

NA
### Category

NA
### Sub Category

NA

**Comment by vishi24** [comment]
| Item                                                                                                  | Description |
|-------------------------------------------------------------------------------------------------------|-------------|
| Implementation of all 10 Endpoints for both the use cases in Strapi plugin - Product and service (time booking). |    DONE         |
| Postman collection for all 10 endpoints and both the use cases.                                       |     DONE         |
| Unit test cases for all 10 endpoints.                                                                |       PENDING      |
| Testing all 10 endpoints and demo of the end-to-end functionality, taking one use case for each scenario. |       PENDING      |
| Development of machine simulation code for Industry 4.0.                                              |      DONE       |
| Plugin development for Industry 4.0.                                                                  |      DONE       |


Testing for different domains is in progress, the working sheet is here - https://docs.google.com/spreadsheets/d/1ll9mcvqfUG8jKBxYK60eEmKuIZSz9mE0LRwT0Y2N9U4/edit#gid=0

Analysis of the strapi data model is here
https://docs.google.com/spreadsheets/d/1zWvyp3L06vU436yTPmyE3D5R5wDImw3DQp8K6LSIzOc/edit#gid=0
