### ISSUE TITLE
Strapi plugin -March -15 Milestones

### ISSUE THREAD

**Issue by vishi24** [beckn/strapi-plugins#25]
## Description

This is the list of milestones for March 15.

## Goals

- [ ] Testing the Strapi plugin for the available domains - https://github.com/beckn/beckn-sandbox/tree/main/artefacts. It should be working properly with these postman collections.
- [ ] Updating the plugin to create the Strapi data models when the plugin is installed.
- [ ] Updating the plugin to give the option for installing dummy data for testing.
- [ ] Creation of scripts to install dummy data.
- [ ] Release of the plugin to Strapi marketplace. Will have a dependency on Strapi.
- [ ] Listing of APIs required for BPP Admin application.
- [ ] Creation of BPP Admin application APIs.

## Expected Outcome

NA

## Acceptance Criteria

NA

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA
### Project Name

NA

### Organization Name:

NA

### Domain

NA

### Tech Skills Needed:

NA

### Complexity

NA

### Category

NA

### Sub Category
NA
